name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: akashashketchum/strapi-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.TAG }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA for tag
        id: vars
        run: echo "TAG=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.vars.outputs.TAG }} ./my-strapi-app
          docker push $IMAGE_NAME:${{ steps.vars.outputs.TAG }}

      - name: Save image tag for Terraform (output)
        run: echo "image_tag=${{ steps.vars.outputs.TAG }}" >> image_tag.txt

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tag
          path: image_tag.txt

