name: Terraform Deploy (Strapi EC2)

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy EC2 via Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout the Terraform repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Download the artifact from CI workflow (image_tag.txt)
      - name: Download Docker Image Tag
        uses: actions/download-artifact@v4
        with:
          name: docker-image-tag

      # Read the tag into an environment variable
      - name: Set image tag as ENV variable
        id: read_tag
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./strapi-terraform-task5

      # Plan
      - name: Terraform Plan
        run: terraform plan -var="image_tag=${{ env.IMAGE_TAG }}" -var="key_name=${{ secrets.KEY_NAME }}"
        working-directory: ./strapi-terraform-task5

      # Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}" -var="key_name=${{ secrets.KEY_NAME }}"
        working-directory: ./strapi-terraform-task5

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
