name: Terraform Deploy (Strapi EC2)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag (e.g. strapi-app:abcd1234)"
        required: true

jobs:
  deploy:
    name: Deploy EC2 via Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout the Terraform repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./strapi-terraform-task5

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="image_tag=${{ github.event.inputs.image_tag }}" -var="key_name=${{ secrets.KEY_NAME }}"
        working-directory: ./strapi-terraform-task5

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ github.event.inputs.image_tag }}" -var="key_name=${{ secrets.KEY_NAME }}"
        working-directory: ./strapi-terraform-task5

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2

